import 'models/pengaturan_model.dart';import 'package:edurecovery/core/app_export.dart';import 'package:edurecovery/widgets/app_bar/appbar_leading_image.dart';import 'package:edurecovery/widgets/app_bar/appbar_subtitle_two.dart';import 'package:edurecovery/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';import 'provider/pengaturan_provider.dart';class PengaturanScreen extends StatefulWidget {const PengaturanScreen({Key? key}) : super(key: key);

@override PengaturanScreenState createState() =>  PengaturanScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => PengaturanProvider(), child: PengaturanScreen()); } 
 }
class PengaturanScreenState extends State<PengaturanScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 11.v), child: Column(children: [Padding(padding: EdgeInsets.only(left: 5.h), child: _buildMegaphoneRow(context, megaphoneImage: ImageConstant.imgUsersAccount, aboutEduRecover: "lbl_account".tr)), SizedBox(height: 7.v), Divider(color: appTheme.blue50), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 4.h), child: _buildVuesaxLinearLogoutRow(context, logoutImage: ImageConstant.imgHelp, logout: "lbl_help_center".tr)), SizedBox(height: 5.v), Divider(color: appTheme.blue50), Divider(color: appTheme.blue50), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 5.h), child: _buildMegaphoneRow(context, megaphoneImage: ImageConstant.imgMegaphone, aboutEduRecover: "msg_about_edurecover".tr)), SizedBox(height: 7.v), Divider(color: appTheme.blue50), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 4.h), child: _buildVuesaxLinearLogoutRow(context, logoutImage: ImageConstant.imgVuesaxLinearLogout, logout: "lbl_logout".tr)), SizedBox(height: 5.v), Divider(color: appTheme.blue50), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 46.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftPrimary, margin: EdgeInsets.only(left: 12.h, top: 18.v, bottom: 18.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_settings_and_privacy".tr)); } 
/// Common widget
Widget _buildMegaphoneRow(BuildContext context, {required String megaphoneImage, required String aboutEduRecover, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: megaphoneImage, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 9.h), child: Text(aboutEduRecover, style: CustomTextStyles.titleMediumMedium.copyWith(color: theme.colorScheme.primary.withOpacity(1)))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 17.adaptSize, width: 17.adaptSize, margin: EdgeInsets.only(top: 3.v, bottom: 4.v))]); } 
/// Common widget
Widget _buildVuesaxLinearLogoutRow(BuildContext context, {required String logoutImage, required String logout, }) { return Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: logoutImage, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 10.h, top: 2.v), child: Text(logout, style: CustomTextStyles.titleMediumRedA700.copyWith(color: appTheme.redA700))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 17.adaptSize, width: 17.adaptSize, margin: EdgeInsets.only(bottom: 7.v))]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
