import 'models/kuis_modul_1_ipa_smp_two_model.dart';import 'package:edurecovery/core/app_export.dart';import 'package:edurecovery/widgets/app_bar/appbar_leading_image.dart';import 'package:edurecovery/widgets/app_bar/appbar_subtitle_two.dart';import 'package:edurecovery/widgets/app_bar/custom_app_bar.dart';import 'package:edurecovery/widgets/custom_elevated_button.dart';import 'package:edurecovery/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';import 'provider/kuis_modul_1_ipa_smp_two_provider.dart';class KuisModul1IpaSmpTwoScreen extends StatefulWidget {const KuisModul1IpaSmpTwoScreen({Key? key}) : super(key: key);

@override KuisModul1IpaSmpTwoScreenState createState() =>  KuisModul1IpaSmpTwoScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KuisModul1IpaSmpTwoProvider(), child: KuisModul1IpaSmpTwoScreen()); } 
 }
class KuisModul1IpaSmpTwoScreenState extends State<KuisModul1IpaSmpTwoScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildComponentOne(context), SizedBox(height: 41.v), Container(width: 277.h, margin: EdgeInsets.only(left: 30.h, right: 52.h), child: Text("msg_apa_yang_menjadi".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleMedium)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 30.h, right: 63.h), child: Row(children: [Padding(padding: EdgeInsets.symmetric(vertical: 6.v), child: Column(children: [Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h))), SizedBox(height: 9.v), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h))), SizedBox(height: 29.v), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h))), SizedBox(height: 9.v), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h)))])), Expanded(child: Container(width: 247.h, margin: EdgeInsets.only(left: 6.h), child: Text("msg_a_curah_hujan_berlebihan_b".tr, maxLines: 5, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium)))]))])), bottomNavigationBar: _buildSebelumnya(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 30.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 21.h, top: 26.v, bottom: 27.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitleTwo(text: "msg_kuis_sains_dalam".tr, margin: EdgeInsets.only(left: 20.h))); } 
/// Section Widget
Widget _buildComponentOne(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 6.v), decoration: AppDecoration.outlinePrimary1, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_nomor_soal".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 7.v), Selector<KuisModul1IpaSmpTwoProvider, TextEditingController?>(selector: (context, provider) => provider.otpController, builder: (context, otpController, child) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});}), SizedBox(height: 6.v)])); } 
/// Section Widget
Widget _buildSebelumnya(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 31.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomElevatedButton(width: 121.h, text: "lbl_sebelumnya".tr, onPressed: () {onTapSebelumnya(context);}), CustomElevatedButton(width: 121.h, text: "lbl_selanjutnya".tr, onPressed: () {onTapSelanjutnya(context);})])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the kuisModul1IpaSmpOneScreen when the action is triggered.
onTapSebelumnya(BuildContext context) { NavigatorService.pushNamed(AppRoutes.kuisModul1IpaSmpOneScreen, ); } 
/// Navigates to the kuisModul1IpaSmpThreeScreen when the action is triggered.
onTapSelanjutnya(BuildContext context) { NavigatorService.pushNamed(AppRoutes.kuisModul1IpaSmpThreeScreen, ); } 
 }
