import 'models/kuis_modul_1_mtk_sd_two_model.dart';import 'package:edurecovery/core/app_export.dart';import 'package:edurecovery/widgets/app_bar/appbar_leading_image.dart';import 'package:edurecovery/widgets/app_bar/appbar_subtitle_two.dart';import 'package:edurecovery/widgets/app_bar/custom_app_bar.dart';import 'package:edurecovery/widgets/custom_elevated_button.dart';import 'package:edurecovery/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';import 'provider/kuis_modul_1_mtk_sd_two_provider.dart';class KuisModul1MtkSdTwoScreen extends StatefulWidget {const KuisModul1MtkSdTwoScreen({Key? key}) : super(key: key);

@override KuisModul1MtkSdTwoScreenState createState() =>  KuisModul1MtkSdTwoScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KuisModul1MtkSdTwoProvider(), child: KuisModul1MtkSdTwoScreen()); } 
 }
class KuisModul1MtkSdTwoScreenState extends State<KuisModul1MtkSdTwoScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildComponentOne(context), SizedBox(height: 40.v), Padding(padding: EdgeInsets.only(left: 30.h), child: Text("lbl_penjumlahan".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 31.h), child: Text("lbl_12_25".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 31.h), child: Row(children: [Padding(padding: EdgeInsets.only(top: 6.v, bottom: 4.v), child: Column(children: [Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h))), SizedBox(height: 9.v), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h))), SizedBox(height: 9.v), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h))), SizedBox(height: 9.v), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h)))])), Container(width: 36.h, margin: EdgeInsets.only(left: 6.h), child: Text("msg_a_37_b_27_c_35_d".tr, maxLines: 4, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium))]))])), bottomNavigationBar: _buildSebelumnya(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 30.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 21.h, top: 26.v, bottom: 27.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_kuis_konsep_dasar".tr)); } 
/// Section Widget
Widget _buildComponentOne(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 6.v), decoration: AppDecoration.outlinePrimary1, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_nomor_soal".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 7.v), Selector<KuisModul1MtkSdTwoProvider, TextEditingController?>(selector: (context, provider) => provider.otpController, builder: (context, otpController, child) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});}), SizedBox(height: 6.v)])); } 
/// Section Widget
Widget _buildSebelumnya(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 31.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomElevatedButton(width: 121.h, text: "lbl_sebelumnya".tr, onPressed: () {onTapSebelumnya(context);}), CustomElevatedButton(width: 121.h, text: "lbl_selanjutnya".tr, onPressed: () {onTapSelanjutnya(context);})])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the kuisModul1MtkSdOneScreen when the action is triggered.
onTapSebelumnya(BuildContext context) { NavigatorService.pushNamed(AppRoutes.kuisModul1MtkSdOneScreen, ); } 
/// Navigates to the hasilSkorKuisModul1MtkSdScreen when the action is triggered.
onTapSelanjutnya(BuildContext context) { NavigatorService.pushNamed(AppRoutes.hasilSkorKuisModul1MtkSdScreen, ); } 
 }
