import 'models/field_change_password_model.dart';import 'package:edurecovery/core/app_export.dart';import 'package:edurecovery/core/utils/validation_functions.dart';import 'package:edurecovery/widgets/app_bar/appbar_leading_image.dart';import 'package:edurecovery/widgets/app_bar/appbar_subtitle_two.dart';import 'package:edurecovery/widgets/app_bar/custom_app_bar.dart';import 'package:edurecovery/widgets/custom_elevated_button.dart';import 'package:edurecovery/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'provider/field_change_password_provider.dart';class FieldChangePasswordScreen extends StatefulWidget {const FieldChangePasswordScreen({Key? key}) : super(key: key);

@override FieldChangePasswordScreenState createState() =>  FieldChangePasswordScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => FieldChangePasswordProvider(), child: FieldChangePasswordScreen()); } 
 }

// ignore_for_file: must_be_immutable
class FieldChangePasswordScreenState extends State<FieldChangePasswordScreen> {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 16.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: Text("msg_current_password".tr, style: CustomTextStyles.titleMediumMedium)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Selector<FieldChangePasswordProvider, TextEditingController?>(selector: (context, provider) => provider.passwordController, builder: (context, passwordController, child) {return CustomTextFormField(controller: passwordController, hintText: "lbl_stev1234567".tr, hintStyle: theme.textTheme.labelLarge!, textInputType: TextInputType.visiblePassword, validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: true);})), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_new_password".tr, style: CustomTextStyles.titleMediumMedium)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Selector<FieldChangePasswordProvider, TextEditingController?>(selector: (context, provider) => provider.newpasswordController, builder: (context, newpasswordController, child) {return CustomTextFormField(controller: newpasswordController, hintText: "lbl_halim12345".tr, hintStyle: theme.textTheme.labelLarge!, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: true);})), SizedBox(height: 32.v), CustomElevatedButton(height: 55.v, text: "lbl_confirmation".tr, margin: EdgeInsets.only(left: 2.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL101, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700, onPressed: () {onTapConfirmation(context);}), SizedBox(height: 5.v)]))))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 46.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftPrimary, margin: EdgeInsets.only(left: 12.h, top: 18.v, bottom: 18.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_change_password".tr), styleType: Style.bgFill); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the pinChangePasswordScreen when the action is triggered.
onTapConfirmation(BuildContext context) { NavigatorService.pushNamed(AppRoutes.pinChangePasswordScreen, ); } 
 }
