import 'models/resume_modul_1_mtk_sd_model.dart';import 'package:edurecovery/core/app_export.dart';import 'package:edurecovery/widgets/app_bar/appbar_leading_image.dart';import 'package:edurecovery/widgets/app_bar/appbar_subtitle_two.dart';import 'package:edurecovery/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';import 'provider/resume_modul_1_mtk_sd_provider.dart';class ResumeModul1MtkSdScreen extends StatefulWidget {const ResumeModul1MtkSdScreen({Key? key}) : super(key: key);

@override ResumeModul1MtkSdScreenState createState() =>  ResumeModul1MtkSdScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ResumeModul1MtkSdProvider(), child: ResumeModul1MtkSdScreen()); } 
 }
class ResumeModul1MtkSdScreenState extends State<ResumeModul1MtkSdScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 18.v), child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 22.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_penjumlahan_dua".tr, style: theme.textTheme.titleMedium), SizedBox(width: 315.h, child: Text("msg_penjumlahan_dua2".tr, maxLines: 6, overflow: TextOverflow.ellipsis, textAlign: TextAlign.justify, style: theme.textTheme.bodyMedium)), SizedBox(height: 13.v), CustomImageView(imagePath: ImageConstant.imgRectangle34150x315, height: 150.v, width: 315.h, radius: BorderRadius.circular(5.h)), SizedBox(height: 8.v), Text("lbl_contoh".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(right: 1.h), child: _buildRow1(context, kolomOne: "lbl_soal".tr, kolomTwo: "lbl_jawaban".tr)), Padding(padding: EdgeInsets.only(right: 1.h), child: _buildRow1(context, kolomOne: "msg_1_35_17_35_17".tr, kolomTwo: "msg_35_17_5235_17_52".tr)), Padding(padding: EdgeInsets.only(right: 1.h), child: _buildRow1(context, kolomOne: "msg_2_82_49_82_49".tr, kolomTwo: "msg_82_49_13182_49_131".tr)), Padding(padding: EdgeInsets.only(right: 1.h), child: _buildRow1(context, kolomOne: "msg_3_126_54_126_54".tr, kolomTwo: "msg_126_54_180126_54_180".tr)), SizedBox(height: 20.v), _buildColumn1(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 30.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 21.h, top: 26.v, bottom: 27.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitleTwo(text: "msg_resume_penjumlahan".tr, margin: EdgeInsets.only(left: 20.h)), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildColumn1(BuildContext context) { return Container(margin: EdgeInsets.only(right: 1.h), decoration: AppDecoration.fillWhiteA, child: Column(children: [Container(width: 315.h, padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 8.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("lbl_konsep_utama".tr, style: CustomTextStyles.labelLargePrimary)])), Container(width: 315.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 7.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_menjelaskan_cara".tr, style: CustomTextStyles.bodySmall12)])), Container(width: 315.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 7.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), Text("msg_mengajarkan_penggunaan".tr, style: CustomTextStyles.bodySmall12)])), Container(width: 315.h, padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 7.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("msg_mendorong_pemahaman".tr, style: CustomTextStyles.bodySmall12)]))])); } 
/// Common widget
Widget _buildRow1(BuildContext context, {required String kolomOne, required String kolomTwo, }) { return Container(padding: EdgeInsets.all(9.h), decoration: AppDecoration.outlineOnPrimaryContainer, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(kolomOne, style: CustomTextStyles.bodySmall12.copyWith(color: theme.colorScheme.primary.withOpacity(1))), Padding(padding: EdgeInsets.only(right: 24.h), child: Text(kolomTwo, style: CustomTextStyles.bodySmall12.copyWith(color: theme.colorScheme.primary.withOpacity(1))))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
