import 'models/kuis_modul_1_mtk_sd_four_model.dart';import 'package:edurecovery/core/app_export.dart';import 'package:edurecovery/widgets/app_bar/appbar_leading_image.dart';import 'package:edurecovery/widgets/app_bar/appbar_subtitle_two.dart';import 'package:edurecovery/widgets/app_bar/custom_app_bar.dart';import 'package:edurecovery/widgets/custom_elevated_button.dart';import 'package:edurecovery/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';import 'provider/kuis_modul_1_mtk_sd_four_provider.dart';class KuisModul1MtkSdFourScreen extends StatefulWidget {const KuisModul1MtkSdFourScreen({Key? key}) : super(key: key);

@override KuisModul1MtkSdFourScreenState createState() =>  KuisModul1MtkSdFourScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => KuisModul1MtkSdFourProvider(), child: KuisModul1MtkSdFourScreen()); } 
 }
class KuisModul1MtkSdFourScreenState extends State<KuisModul1MtkSdFourScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildNavbarAtas(context), SizedBox(height: 43.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("lbl_pembagian".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 31.h), child: Text("lbl_48_6".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 31.h), child: Row(children: [Padding(padding: EdgeInsets.only(top: 6.v, bottom: 4.v), child: Column(children: [Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h))), SizedBox(height: 9.v), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h))), SizedBox(height: 9.v), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h))), SizedBox(height: 9.v), Container(height: 12.adaptSize, width: 12.adaptSize, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.gray400, width: 1.h)))])), Container(width: 28.h, margin: EdgeInsets.only(left: 6.h), child: Text("msg_a_8_b_6_c_7_d".tr, maxLines: 4, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium))]))])), bottomNavigationBar: _buildSebelumnya(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 30.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 21.h, top: 26.v, bottom: 27.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_kuis_konsep_dasar".tr)); } 
/// Section Widget
Widget _buildNavbarAtas(BuildContext context) { return Container(decoration: AppDecoration.outlinePrimary1, child: Selector<KuisModul1MtkSdFourProvider, TextEditingController?>(selector: (context, provider) => provider.otpController, builder: (context, otpController, child) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});})); } 
/// Section Widget
Widget _buildSebelumnya(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 23.h, right: 23.h, bottom: 31.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomElevatedButton(width: 121.h, text: "lbl_sebelumnya".tr, onPressed: () {onTapSebelumnya(context);}), CustomElevatedButton(width: 121.h, text: "lbl_selanjutnya".tr, onPressed: () {onTapSelanjutnya(context);})])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the kuisModul1MtkSdThreeScreen when the action is triggered.
onTapSebelumnya(BuildContext context) { NavigatorService.pushNamed(AppRoutes.kuisModul1MtkSdThreeScreen, ); } 
/// Navigates to the kuisModul1MtkSdFiveScreen when the action is triggered.
onTapSelanjutnya(BuildContext context) { NavigatorService.pushNamed(AppRoutes.kuisModul1MtkSdFiveScreen, ); } 
 }
