import 'models/sub_help_model.dart';import 'package:edurecovery/core/app_export.dart';import 'package:edurecovery/widgets/app_bar/appbar_leading_image.dart';import 'package:edurecovery/widgets/app_bar/appbar_subtitle_two.dart';import 'package:edurecovery/widgets/app_bar/custom_app_bar.dart';import 'package:edurecovery/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'provider/sub_help_provider.dart';class SubHelpScreen extends StatefulWidget {const SubHelpScreen({Key? key}) : super(key: key);

@override SubHelpScreenState createState() =>  SubHelpScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => SubHelpProvider(), child: SubHelpScreen()); } 
 }
class SubHelpScreenState extends State<SubHelpScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 16.v), child: Column(children: [Container(width: 84.h, padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 1.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder14), child: Text("lbl_today".tr, style: CustomTextStyles.bodyMediumMulish)), SizedBox(height: 11.v), _buildSubHelp(context), SizedBox(height: 479.v), Selector<SubHelpProvider, TextEditingController?>(selector: (context, provider) => provider.messageController, builder: (context, messageController, child) {return CustomTextFormField(controller: messageController, hintText: "msg_type_a_message".tr, hintStyle: CustomTextStyles.titleSmallOnPrimaryContainer, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(25.h, 21.v, 15.h, 25.v), child: CustomImageView(imagePath: ImageConstant.imgAttachment, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 70.v), suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 23.v, 23.h, 23.v), child: CustomImageView(imagePath: ImageConstant.img22send, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 70.v), contentPadding: EdgeInsets.symmetric(vertical: 24.v), borderDecoration: TextFormFieldStyleHelper.outlineIndigo);})]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVector, margin: EdgeInsets.only(left: 24.h, top: 27.v, bottom: 28.v), onTap: () {onTapVector(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_help_center".tr), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildSubHelp(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 15.h, right: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgEllipse1848x48, height: 48.adaptSize, width: 48.adaptSize, radius: BorderRadius.circular(24.h), margin: EdgeInsets.only(bottom: 85.v)), Expanded(child: Container(margin: EdgeInsets.only(left: 12.h), padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 5.v), decoration: AppDecoration.fillBlueGray.copyWith(borderRadius: BorderRadiusStyle.customBorderBL20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), Container(width: 230.h, margin: EdgeInsets.only(right: 5.h), child: Text("msg_halo_stevanus79".tr, maxLines: 6, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumMulishSecondaryContainer.copyWith(height: 1.43)))])))])); } 

/// Navigates to the previous screen.
onTapVector(BuildContext context) { NavigatorService.goBack(); } 
 }
