import 'models/profile_one_model.dart';import 'package:edurecovery/core/app_export.dart';import 'package:edurecovery/presentation/home_page/home_page.dart';import 'package:edurecovery/widgets/app_bar/appbar_subtitle_two.dart';import 'package:edurecovery/widgets/app_bar/appbar_trailing_image.dart';import 'package:edurecovery/widgets/app_bar/custom_app_bar.dart';import 'package:edurecovery/widgets/custom_bottom_bar.dart';import 'package:edurecovery/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'provider/profile_one_provider.dart';class ProfileOneScreen extends StatefulWidget {const ProfileOneScreen({Key? key}) : super(key: key);

@override ProfileOneScreenState createState() =>  ProfileOneScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ProfileOneProvider(), child: ProfileOneScreen()); } 
 }

// ignore_for_file: must_be_immutable
class ProfileOneScreenState extends State<ProfileOneScreen> {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildEditProfile(context), SizedBox(width: 168.h, child: Divider(color: theme.colorScheme.primary.withOpacity(1), indent: 43.h)), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_riwayat_pembelajaran".tr, style: CustomTextStyles.titleSmallSecondaryContainer)), SizedBox(height: 13.v), Divider(), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_1_konsep_dasar".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 12.v), Divider(), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_2_pendidikan_finansial".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 11.v), Divider(), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_1_biologi_kehidupan".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 12.v), Divider(), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(left: 26.h), child: Text("msg_3_teknologi_penanggulangan".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 9.v), Divider(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_profile".tr), actions: [AppbarTrailingImage(imagePath: ImageConstant.img44Setting, margin: EdgeInsets.symmetric(horizontal: 20.h, vertical: 23.v))], styleType: Style.bgFill); } 
/// Section Widget
Widget _buildEditProfile(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 43.h), decoration: AppDecoration.outlinePrimary, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 18.v), CustomImageView(imagePath: ImageConstant.imgEllipse17, height: 156.adaptSize, width: 156.adaptSize, radius: BorderRadius.circular(78.h)), SizedBox(height: 8.v), Text("lbl_stevanus79".tr, style: CustomTextStyles.titleSmallSecondaryContainerMedium), SizedBox(height: 18.v), CustomElevatedButton(height: 50.v, text: "lbl_edit_profile".tr, margin: EdgeInsets.only(left: 6.h, right: 4.h), buttonStyle: CustomButtonStyles.outlinePrimary, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700), SizedBox(height: 27.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(children: [Text("lbl_pembelajaran".tr, style: CustomTextStyles.titleSmallSecondaryContainerMedium), SizedBox(height: 6.v), SizedBox(width: 125.h, child: Divider(color: theme.colorScheme.primary.withOpacity(1)))])), GestureDetector(onTap: () {onTapTxtPelatihan(context);}, child: Padding(padding: EdgeInsets.only(bottom: 13.v), child: Text("lbl_pelatihan".tr, style: CustomTextStyles.titleSmallSecondaryContainerMedium)))])))])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.home2bluea70002: return AppRoutes.homePage; case BottomBarEnum.User: return "/"; case BottomBarEnum.keepminusprimarycontainer: return "/"; case BottomBarEnum.Lock: return "/"; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.homePage: return HomePage.builder(context); default: return DefaultWidget();} } 
/// Navigates to the profileTwoScreen when the action is triggered.
onTapTxtPelatihan(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileTwoScreen, ); } 
 }
