import 'models/registrasi_model.dart';import 'package:edurecovery/core/app_export.dart';import 'package:edurecovery/core/utils/validation_functions.dart';import 'package:edurecovery/widgets/custom_elevated_button.dart';import 'package:edurecovery/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'provider/registrasi_provider.dart';class RegistrasiScreen extends StatefulWidget {const RegistrasiScreen({Key? key}) : super(key: key);

@override RegistrasiScreenState createState() =>  RegistrasiScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => RegistrasiProvider(), child: RegistrasiScreen()); } 
 }

// ignore_for_file: must_be_immutable
class RegistrasiScreenState extends State<RegistrasiScreen> {GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Center(child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom), child: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 29.v), CustomImageView(imagePath: ImageConstant.imgRectangle2624, height: 38.v, width: 215.h, alignment: Alignment.center), SizedBox(height: 34.v), Align(alignment: Alignment.center, child: Text("lbl_registration".tr, style: theme.textTheme.titleLarge)), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_email".tr, style: CustomTextStyles.titleMediumMedium)), SizedBox(height: 11.v), _buildEmail(context), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_username".tr, style: CustomTextStyles.titleMediumMedium)), SizedBox(height: 10.v), _buildUserName(context), SizedBox(height: 11.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_password".tr, style: CustomTextStyles.titleMediumMedium)), SizedBox(height: 10.v), _buildPassword(context), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("msg_confirm_password".tr, style: CustomTextStyles.titleMediumMedium)), SizedBox(height: 11.v), _buildConfirmPassword(context), SizedBox(height: 24.v), _buildRegistrationButton(context), SizedBox(height: 12.v), Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapTxtAlreadyhavean(context);}, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_already_have_an2".tr, style: CustomTextStyles.labelLargeff000001), TextSpan(text: "lbl_enter_here".tr, style: CustomTextStyles.labelLargeff2a7fff)]), textAlign: TextAlign.left)))]))))))); } 
/// Section Widget
Widget _buildEmail(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h), child: Selector<RegistrasiProvider, TextEditingController?>(selector: (context, provider) => provider.emailController, builder: (context, emailController, child) {return CustomTextFormField(controller: emailController, hintText: "lbl_email2".tr, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;});})); } 
/// Section Widget
Widget _buildUserName(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 1.h), child: Selector<RegistrasiProvider, TextEditingController?>(selector: (context, provider) => provider.userNameController, builder: (context, userNameController, child) {return CustomTextFormField(controller: userNameController, hintText: "lbl_username2".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});})); } 
/// Section Widget
Widget _buildPassword(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h), child: Selector<RegistrasiProvider, TextEditingController?>(selector: (context, provider) => provider.passwordController, builder: (context, passwordController, child) {return CustomTextFormField(controller: passwordController, hintText: "lbl_password2".tr, textInputType: TextInputType.visiblePassword, validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: true);})); } 
/// Section Widget
Widget _buildConfirmPassword(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 2.h), child: Selector<RegistrasiProvider, TextEditingController?>(selector: (context, provider) => provider.confirmPasswordController, builder: (context, confirmPasswordController, child) {return CustomTextFormField(controller: confirmPasswordController, hintText: "msg_confirm_password2".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: true);})); } 
/// Section Widget
Widget _buildRegistrationButton(BuildContext context) { return CustomElevatedButton(height: 55.v, text: "lbl_registration".tr, margin: EdgeInsets.only(left: 2.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL101, buttonTextStyle: CustomTextStyles.titleMediumWhiteA700); } 
/// Navigates to the loginScreen when the action is triggered.
onTapTxtAlreadyhavean(BuildContext context) { NavigatorService.pushNamed(AppRoutes.loginScreen, ); } 
 }
