import 'models/resume_modul_1_ipa_smp_model.dart';import 'package:edurecovery/core/app_export.dart';import 'package:edurecovery/widgets/app_bar/appbar_leading_image.dart';import 'package:edurecovery/widgets/app_bar/appbar_subtitle_two.dart';import 'package:edurecovery/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';import 'provider/resume_modul_1_ipa_smp_provider.dart';class ResumeModul1IpaSmpScreen extends StatefulWidget {const ResumeModul1IpaSmpScreen({Key? key}) : super(key: key);

@override ResumeModul1IpaSmpScreenState createState() =>  ResumeModul1IpaSmpScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => ResumeModul1IpaSmpProvider(), child: ResumeModul1IpaSmpScreen()); } 
 }
class ResumeModul1IpaSmpScreenState extends State<ResumeModul1IpaSmpScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 17.v), child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 22.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 270.h, margin: EdgeInsets.only(right: 45.h), child: Text("msg_perilaku_alam_sebagai".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleMedium)), SizedBox(height: 2.v), SizedBox(width: 315.h, child: Text("msg_perilaku_alam_memegang".tr, maxLines: 4, overflow: TextOverflow.ellipsis, textAlign: TextAlign.justify, style: theme.textTheme.bodyMedium)), SizedBox(height: 15.v), CustomImageView(imagePath: ImageConstant.imgRectangle341, height: 150.v, width: 315.h, radius: BorderRadius.circular(5.h)), SizedBox(height: 26.v), _buildResumeModul1IPA(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 30.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 21.h, top: 26.v, bottom: 27.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitleTwo(text: "msg_resume_1_perilaku".tr, margin: EdgeInsets.only(left: 20.h)), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildResumeModul1IPA(BuildContext context) { return Container(decoration: AppDecoration.fillWhiteA, child: Column(children: [Container(width: 315.h, padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 7.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), Container(width: 289.h, margin: EdgeInsets.only(right: 5.h), child: Text("msg_gempa_bumi_gempa".tr, maxLines: 7, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmall12))])), Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 7.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), SizedBox(width: 292.h, child: Text("msg_letusan_gunung_letusan".tr, maxLines: 6, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmall12))])), Container(width: 315.h, padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 7.v), decoration: AppDecoration.outlineOnPrimaryContainer1, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), Container(width: 275.h, margin: EdgeInsets.only(right: 19.h), child: Text("msg_banjir_banjir_dapat".tr, maxLines: 6, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmall12))]))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
